### ISSUE TITLE
Question: How could api urls be better grouped?

### ISSUE THREAD

**Issue by Wirzi** [marcgibbons/django-rest-swagger#107]
![bildschirmfoto 2014-08-19 um 17 29 19](https://cloud.githubusercontent.com/assets/1812094/3968324/ca4ce630-27b5-11e4-89bc-70afca83dd2d.png)

Any idea how to get not "api" as title? I would like to have groups like:

"my-locations"
"opening-times"
....

Thanks for help ;)

**Comment by ariovistus** [comment]
A general - purpose solution would be to add a list of regexes to match against in swagger settings, something like

```python
'API_GROUPS': [
    {
        'description': "Operations on my locations",
        'matches':  '^/api/admin/my-locations/',
    }
]
```

that would be obnoxious, though. a quicker solution would be to add a simple int parameter to swagger settings that specifies how many path parts 'count' as part of the same group, e.g.
```'GROUP_PART_COUNT': 1```
would be current behavior,
```'GROUP_PART_COUNT': 3```
would suite @Wirzi's example

I guess you could just make it automatically group viewsets. It should probably be doing that anyways, since it looks like drs wants to shove some docstring into the description.

though I should probably have a look at what drs is doing and what is possible before spitballing here..

**Comment by marcgibbons** [comment]
DRF now handles schema generation + grouping
