### ISSUE TITLE
Cannot load resource documentation

### ISSUE THREAD

**Issue by sloria** [marcgibbons/django-rest-swagger#13]
I set up django-rest-swagger as specified in the README. When I navigate to my api root in the django-rest-swagger interface, I get a loading prompt saying `fetching resource list: http://localhost:8000/rs/` that remains indefinitely.

I have not been able to get it to work, so I have to revert to django-rest-docs for now.

Any idea why this might be happening?

**Comment by brianjgeiger** [comment]
We are running into a problem where we are attempting to use override our JSON renderer in order to make the output match the JSON API spec. We are using https://github.com/django-json-api/django-rest-framework-json-api, but any new JSON renderer will run into the same problem.

#46, or something similar, looks like the right kind of solution for this as we need to use a different default JSON renderer in order to make this work. We'll be happy to make a PR with the proper solution, but I thought I'd mention in case there was a reason not to go with #46 aside from the fact that it seemed unnecessary at the time.
