### ISSUE TITLE
BooleanField rendered as a select instead of a checkbox

### ISSUE THREAD

**Issue by duduklein** [marcgibbons/django-rest-swagger#225]
Hi, 

I have BoolenField declared like this: ```BooleanField(default=False)```, which is being rendered as a select with 3 options (""; "true", "false"):
```
<select class="parameter" name="bat">
    <option selected="" value=""></option>
    <option value="true">true</option>
    <option value="false">false</option>
</select>
```

According to [django rest docs](http://www.django-rest-framework.org/api-guide/fields/#booleanfield), this field does not accept an "null" value, so there are only 2 options available (true or false) and it correspondes to  ```django.db.models.fields.BooleanField ```, which is a checkbox when rendered as a django form. 
The rendered select should correspond to the ```NullBooleanField```.

Besides the fact that there are 3 options instead of 2, I specified the ```default=False``` and in this case, the selected value by default is ```""```` (1st option).

Are those bugs or the expected behavior for the rest interface / swagger?

If those are bugs, I'm willing to help fix them, just give me some light on where the html code is generated please.

Thanks

**Comment by ariovistus** [comment]
I see no reason why this should be expected behavior. The html is generated by swagger (which you should probably leave alone) based on data sent to it by the django-rest-swagger apis.

a cursory look through the source suggests DRS isn't explicitly passing true,false,null to swagger, so I'd guess swagger is automatically generating these based on the type. Don't know if there is a supported way to override, but if there is, build_form_parameters in introspectors.py is a good place to start looking. [swagger spec 1.2](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md) is another.

**Comment by duduklein** [comment]
Hi, I have made some progress.
Using `BooleanField(initial="false")` and the fix I proposed at https://github.com/marcgibbons/django-rest-swagger/issues/226, I got the following:
```
<select class="parameter" name="bat">
    <option value="true">true</option>
    <option selected="" value="false">false (default)</option>
</select>
```

but my field is still not marked as required, even if the json response contains:
```bat: 
defaultValue: "false"
description: null
format: "boolean"
readOnly: false
required: true
type: "boolean"
```
Donc require = true, but the select is still not being rendered as "required".

Regarding the initial value, I think django-rest-swagger should convert `True` and `False` to `"true"` and `"false"`.

Do you agree? If yes, where should this "conversion" take place?
