### ISSUE TITLE
Move to Swagger 2.0

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#250]
[Migration Guide](https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide)

**Comment by sloria** [comment]
+1. This would be great. Maintainer(s): please let us know if there's anything we can do to help move this forward.

**Comment by wing328** [comment]
+1. I'd experience working with both swagger 1.2 and 2.0. Let me know if I can help.

**Comment by jason-kane** [comment]
This is a rather hideous pile of outrageous test-less hackery.  It mostly works, at least Cigar shop looks plausible:

https://github.com/jason-kane/django-rest-swagger/tree/swagger2

Most of the changes are out at the view instead of inside docgenerator which is where they belong.  Frankly the 2.0 structure is so different much of docgenerator could/should be redone.  It wouldn't be very difficult to support both 1.2 and 2.0.

Anyway, for whatever it is worth.  2.0 support will have to be baked in eventually.

**Comment by maccesch** [comment]
+1

**Comment by arw180** [comment]
+1

**Comment by CodyMorris** [comment]
+1

**Comment by benjamincrom** [comment]
+1

**Comment by ernestm** [comment]
+1

**Comment by raunak1789** [comment]
+1

**Comment by goinnn** [comment]
+1

**Comment by LyleScott** [comment]
+1

**Comment by pankeshang** [comment]
+1

**Comment by mailbackwards** [comment]
+1

**Comment by JanickRoss** [comment]
+1

**Comment by helgi** [comment]
+1

**Comment by danielquinn** [comment]
+1

**Comment by resalisbury** [comment]
+1

**Comment by spreeker** [comment]
+1

**Comment by monk8800** [comment]
+1

**Comment by cyan198** [comment]
+1

**Comment by andypapas** [comment]
+1

**Comment by zadoev** [comment]
+1

**Comment by aapris** [comment]
+1

**Comment by marcgibbons** [comment]
Done in v2.

**Comment by vtisnado** [comment]
+1
