### ISSUE TITLE
Include Css source files (less or scss)?

### ISSUE THREAD

**Issue by jebsky** [marcgibbons/django-rest-swagger#272]
I was wondering if you used a complier to generate the .css files. If you did it would be sweet if you put them in the repo. When I looked into it it seems swagger-gui uses less

Thanks
Jeff

**Comment by ariovistus** [comment]
I have a feeling they just got slapped in when this project was started using whatever was in swagger at the time. Certainly, I would prefer it if the source were inline, and also where it came from/what version were documented. 
Any opinions on how to do this? git submodule?
Should only source files be included, since the css is really more of a build artifact?

**Comment by ariovistus** [comment]
actually, it looks like swagger-ui keeps a dist folder in their repo
