### ISSUE TITLE
Add possibility of generating 'header' parameters

### ISSUE THREAD

**Issue by marcgibbons** [marcgibbons/django-rest-swagger#3]
This may not be useful...

**Comment by sbussetti** [comment]
Consider this (actual real world) use case.

I have an API that is location dependent.  All results returned by the API depend on the geographical location reported by the user.  Rather than force developers working against my API to always provide lat/lng in their query strings, they can provide it in a single location in their code by setting a Location header on all their requests.

Being able to set ad-hoc headers in the same way that you can set an api_key for the Authorization header would be extremely useful.

Another use case for this would be APIs with polymorphic content based on the Accept header.  Developers testing my API should be able to set that header in order to specify their desired response type.

**Comment by miguelfg** [comment]
+1 @sbussetti
