### ISSUE TITLE
Wrongly recognized Django url pattern

### ISSUE THREAD

**Issue by shnela** [marcgibbons/django-rest-swagger#342]
Below description is copied from [my stackoverflow post][1].

  [1]: http://stackoverflow.com/questions/31797515/swagger-ui-wrongly-recognized-django-url-pattern

## Intorudction ##

I've implemented rest API using `django-rest-framework`.

I've decided to implement batch operations, where ids were neccessary, in two ways:

 1. By sending ids in url, separated with '/':

        url(r'^tubes/(?P<ids>(([0-9]+/)+))$', manage_tubes, name='manage_tubes'),
    Example request:
    >http://127.0.0.1:8000/tubes/0/1/10/

 2. By sending ids in POST body as a json array:

        url(r'^tubes/(?P<operation>(create|delete|get))/$', manage_tubes_json, name='manage_tubes_json'),
    Example request:
    >http://127.0.0.1:8000/tubes/get

    with following body:
    >[0, 1, 10]

This works well, but I've problem with `django-rest-swagger`. Actually with `swagger UI`.

## Problem ##

Swagger didn't recognized my url patterns very well...

It sees urls as follows:

  1. >/tubes/{ids}+))

     (redundant '+))' )
  2. >POST /tubes/{operation})/

     (redundant ')' )

Is my `urls.py` file incorrect or maybe I should define url paramters somehow?

**Comment by iambibhas** [comment]
Yes, same as this. For me the pattern is - 

    ^(?P<session>[\d\-]{5})/(?P<entity>(cluster|block|district|assembly|parliament|pincode))/$

and the UI shows - 

    /api/{session}/{entity})/

This is breaking the API doc.

**Comment by marcgibbons** [comment]
I don't think this is something that can done, and I suggest considering following a more restful pattern, specifically, using HTTP methods to capture "operations" rather than the URI.

Something like:
`url(r'^tubes/(?P<operation>(create|delete|get))`

Should be

GET /tubes (list)
DELETE /tubes/<id>
POST /tubes (create)
GET /tubes/<id> (individual object)

As for the second example, something more "restful" would mean using a query parameter or filter for the entities, or, making the routes based on the resource.

i.e. `/session?entity=cluster`
or /cluster/session
