### ISSUE TITLE
UI Config Settings / Theming

### ISSUE THREAD

**Issue by Miserlou** [marcgibbons/django-rest-swagger#347]
It'd be nice if some of the UI elements could be defined via the SWAGGER_SETTINGS. For instance, the Title of the page (both the title tag and the H1, etc,) and a link to a stylesheet to use.

On a related note - are there any examples on different Swagger themes to use?

**Comment by monk8800** [comment]
Was curious about the same thing as well, but couldn't find any reference to extending UI via settings resorted to extending the swagger template

**Comment by kibernick** [comment]
+1

**Comment by 1Map** [comment]
+1

**Comment by littlepea** [comment]
+1

Would be amazing to be able to switch to this UI fork: https://github.com/jensoleg/swagger-ui

**Comment by monk8800** [comment]
+1

**Comment by marcgibbons** [comment]
Hi everyone,
Customization of themes is a great idea (and am shipping template overrides w/ 2.0.5 documentation to come).
Since v2, it is possible to host the OpenAPI/Swagger spec independently from the UI, giving the flexibility to host your own front-end independently from the schema generator (i.e. the OpenAPIRenderer).
