### ISSUE TITLE
GeoDjango fields declared as string when type is GeoJSON

### ISSUE THREAD

**Issue by DavidJFelix** [marcgibbons/django-rest-swagger#429]
If you use any of these fields on your model:

https://docs.djangoproject.com/en/1.9/ref/contrib/gis/model-api/

and include them in a DRF serializer's `Meta.fields` tuple, they'll be identified as a string, when in reality they're a GeoJSON object.

**Comment by DavidJFelix** [comment]
I think [this method](https://github.com/marcgibbons/django-rest-swagger/blob/develop/rest_framework_swagger/introspectors.py#L488) is where "string" is coming from. I'd like to assist with adding Geo features, especially since both Django and DRF list them as supported avenues in their docs, however, I may need help with testing some of the edge cases and desired Django version supports. I'm only really able to test 1.9 at the time.

**Comment by marcgibbons** [comment]
@DavidJFelix The schema generation has been pushed up to DRF and for this first release, only string types are supported, though likely will be extended. For a parameter in formData, this can  probably only be a string formData parameter since the OpenAPI specification only supports JS primitives, but could work in a general body.

This answer probably doesn't help much...

**Comment by marcgibbons** [comment]
Typing is on its way: https://github.com/tomchristie/django-rest-framework/issues/4422
