### ISSUE TITLE
Documentation output in markdown

### ISSUE THREAD

**Issue by Stekot** [marcgibbons/django-rest-swagger#441]
HTML format as output is not very useful if somebody needs to make api docs a part of a bigger part of the documentation. For our purposes Markdown is the best format, what do you think about django task that would print it into console/file?

**Comment by jmbowman** [comment]
Have you seen [Swagger2Markup](https://github.com/Swagger2Markup/swagger2markup)?  Seems like that would cover the need (and there's also [swagger2rst](https://github.com/Arello-Mobile/swagger2rst) for reStructuredText output).  It's been a little while since I used django-rest-swagger, but I thought you could get the generated Swagger files in addition to the HTML generated by Swagger UI.  Would you need this functionality baked directly into django-rest-swagger, or could you just use one of those tools in your workflow?

**Comment by marcgibbons** [comment]
This is outside the scope of this project, however, now that DRF uses CoreAPI, it is possible to translate the OpenAPI spec into other formats.
