### ISSUE TITLE
Swagger 2.0 roadmap

### ISSUE THREAD

**Issue by stevefox** [marcgibbons/django-rest-swagger#443]
I noticed you have a features/swagger-2 branch. Is this to add support for Swagger 2.0? Do you have a road map and/or would like help here?

**Comment by marcgibbons** [comment]
Hey @stevefox - thanks for raising the issue.

Yes, I started fiddling with the 2.0 spec and experimenting with ways to move this project forward. I am looking for help for both maintaining the existing version, going through existing PRs and issues as well as working on a new version which I foresee as a breaking change.

As for the roadmap, here is what I was thinking of:

- Python 3.4+, Django 1.9 + (maybe 1.8LTS?) and DRF 3.3+
- Use the Swagger 2.0 spec; expose a single spec file rather than calling separate HTTP requests. Performance is a problem when we have dozens of simultaneous requests.
- Use Python objects / dictionaries to override / customize Swagger properties for serializers, views and viewsets rather than parsing YAML in the docstring. Thinking of using some sort of class on the serializers, or views which would allow developers to modify documentation
- Use DRF serializers to validate and render the Swagger spec
- Support multiple "instances" of swagger with isolated configurations. This could be useful for supporting multiple APIs in a single Django codebase. This could be private vs. internal API, different versions, etc.
- Add introspection on a view's parsers and renderers to present appropriate parameters - i.e. only use form fields if the endpoint accepts form data, otherwise use body, etc.

The original driving force behind this project (and its predecessor django-rest-framework-docs) stemmed from refusing to write documentation for an API I was building for an agency client. The idea of opening Word (gasps) each time code was changed was revolting to me (in 2012...) and wanted something to automate this process.  

Moving forward, I'd like to keep introspection and auto-generated docs at the core of the project. If we have to manually document the API in the codebase, we are following the same broken paradigm of updating a Word doc each time code changes. Better off writing a swagger spec in raw JSON/YAML and having 100%. However, I do want to make customization easier,  intuitive and more "pythonic" / "django-esque".

Would love to hear your thoughts and suggestions!

**Comment by ticosax** [comment]
@marcgibbons Did you already consider transferring the project to [jazzband](https://jazzband.co/) ?

**Comment by tarkatronic** [comment]
@marcgibbons Is there a list of issues to be worked on here? Is there any way for more people to start jumping on this effort? I may be interested in contributing some effort toward making this a reality.

**Comment by marcgibbons** [comment]
@tarkatronic Yes, that would be great! I'm doing heavy contracting right now, so availability is limited, but I will have some time the first week of July to hopefully ship some sort of alpha.

I have not broken any issues, mostly prototyping / proof of concept. You can see where I'm at in feature/swagger-2, but take it with a grain of salt.

Also @tomchristie is working on rolling out CoreAPI in DRF 3.4, so much of the introspection that is done by Django REST Swagger today will be done by DRF/CoreAPI, so I don't want to invest too heavily until we get a better sense of what that will look like.

**Comment by tarkatronic** [comment]
@marcgibbons I did see that thread, which somewhat sparked my interest. I don't know hardly anything about the inner workings of this package, but given the work happening in DRF, is there perhaps some decoupling that needs to be done between the introspection and rendering? Also, have you put much work yet into updating the tests? I think that might be the most appropriate starting point, given our discussions in the other threads.

**Comment by tomchristie** [comment]
@marcgibbons Much progress with the https://github.com/tomchristie/django-rest-framework/pull/4179 branch. I'll be drawing up the API guide docs for it shortly so everything oughta start to come together pretty quickly.

**Comment by tarkatronic** [comment]
@marcgibbons I've branched off from your swagger-2 branch and started a bit of work. This may be a good time to either take this conversation offline or move it to new ticket(s). So far:
* pylint failure signals a failure in tox
* Testing grid is expanded to include 1.8 and 1.10
* Imports have been cleaned up to avoid circulars, except one that pylint is reporting and I *cannot* find.
* Tests/paths have been fixed up so everything is now passing, except for 3 which represent real failures against Django 1.10
You can see my work here: https://github.com/tarkatronic/django-rest-swagger/tree/feature/swagger-2

**Comment by marcgibbons** [comment]
@tomchristie awesome!
@tarkatronic great!  the circular import error is coming from here https://github.com/marcgibbons/django-rest-swagger/blob/feature/swagger-2/rest_framework_swagger/urlparser.py#L172. the wildcard imports are ok in the __init__ modules, but nowhere else.

**Comment by marcgibbons** [comment]
Progress update:
The 2.0 roadmap has shifted and is planned to release alongside DRF 3.4 and use CoreAPI. Much of the introspection this project has been responsible for generating is being rolled up into the Django REST framework core. Stay tuned!
