### ISSUE TITLE
The swagger urls are not using the SCRIPT_NAME header

### ISSUE THREAD

**Issue by bobkarreman** [marcgibbons/django-rest-swagger#494]
I have a django app deployed in a subfolder with a reverse proxy.

For django to work properly I set the SCRIPT_NAME header, but swagger is not using that.
Causing all urls to be wrong.

**Comment by marcgibbons** [comment]
@bobkarreman Can you be more specific in describing the problem?

**Comment by bobkarreman** [comment]
Yes of course, sorry if its not clear.

I have a django app with django-rest-framework and django-rest-swagger deployed like this:

/my-subfolder/actual-django-folder/swagger/
So my reverse proxy in nginx is serving my django_app on /my-subfolder/ while my django app code wise only knows about /actual-django-folder/* so when I load the swagger json all the path's in there only contain the /actual-django-folder missing the my-subfolder causing the swagger-ui to send the requests to the wrong url.
So the urls its pointing to is /actual-django-folder/api-endpoint while it should point to /my-subfolder/actual-django-folder/api-endpoint.

I had the same issue in the beginning with the django-admin but that I fixed by setting the SCRIPT_NAME header from nginx.

@marcgibbons I hope it makes a bit more sense now :-)

**Comment by marcgibbons** [comment]
@bobkarreman Yes, thank you! To summarize then, the renderers are working correctly, but the URLs in the specification to the endpoints is incorrect?

This is likely an issue to open on the Django REST Framework project, since it is responsible for generating the schema describing the API and setting the URIs.

However, I am working on providing configurations and overrides in this project, so we could set a base path and all the endpoints then become relative to that base.

**Comment by bobkarreman** [comment]
@marcgibbons Thnx! I will create a ticket on the Django REST Framework then as well to make sure that the schema generation is done correctly on that side.

And allowing to overwrite the base path in a configuration also seems like a nice alternative option.

**Comment by tomchristie** [comment]
Resolved by 3.4.1.  `SchemaGenerator(url=...)` or `DefaultRouter(schema_url=...`

**Comment by marcgibbons** [comment]
Thank you! Closing.
