### ISSUE TITLE
how could i get the POST Parameters

### ISSUE THREAD

**Issue by iawia002** [marcgibbons/django-rest-swagger#574]
i have written the `serializer_class`, but Swagger doesn't show the parameters that i need (just like the second picture)

``` python
class NodeViewSet(viewsets.ViewSet):
    serializer_class = serializers.NodeSerializer
```

<img width="477" alt="2016-10-27 11 49 11" src="https://cloud.githubusercontent.com/assets/9134003/19753960/b0dfb0c2-9c3b-11e6-95f3-9c19f8150c34.png">
<img width="908" alt="2016-10-27 11 49 21" src="https://cloud.githubusercontent.com/assets/9134003/19753964/ba35b9be-9c3b-11e6-831c-db35cf8eb841.png">

i use django-rest-swagger 2.0.7 and django rest framework 3.5.1

**Comment by angvp** [comment]
Could you paste the code of NodeSerializer ?

**Comment by iawia002** [comment]
yeah

```python
class NodeSerializer(serializers.Serializer):
    node_type = serializers.ChoiceField(
    ……
    )
    title = serializers.CharField(
    )
    content = serializers.CharField(
    )
```

**Comment by slykar** [comment]
It's because the `OpenAPI Renderer` is using `CoreAPI Renderer` to supply `Swagger` with schema.
The problem is, `CoreAPI` does not support nested fields definition.

However, DRF already provides a full schema as metadata.
http://www.django-rest-framework.org/api-guide/metadata/

It seem to also be used internally for the Browseable API.
The way `OpenAPI` is generated should use metadata instead relying on the `CoreAPI Renderer`.

**Comment by marcgibbons** [comment]
@iawia002 Sorry for not responding sooner.

Is this still an issue in the latest versions?

**Comment by iawia002** [comment]
Let me have a try

**Comment by iawia002** [comment]
😕  still got this problem

**Comment by WisZhou** [comment]
Use viewsets.ModelViewSet or viewsets.GenericViewSet instead of viewsets.ViewSet  can render the parameters.

**Comment by iawia002** [comment]
@WisZhou is right, so I'm going to close this issue.

**Comment by johnyoonh** [comment]
If I want to add a customer parameter for viewsets.ViewSet POST method, is there something I can do?
