### ISSUE TITLE
The UI does not render once djoser URLs are added 

### ISSUE THREAD

**Issue by 5ak3t** [marcgibbons/django-rest-swagger#584]
Once [djoser](https://github.com/sunscrapers/djoser) URLs are added into the project urls the UI does not render. And it throws the following error:

TypeError at /api-UI/
`getattr(): attribute name must be string`

[Stacktrace](https://gist.github.com/anonymous/04c923a2171d4e1f44231c3510ddf981.js )

**Comment by svschannak** [comment]
I got the same problem here. Is this a djoser or swagger problem?

**Comment by mcranston18** [comment]
@5ak3t @svschannak Have either of you figured out a solution to this?

**Comment by marcgibbons** [comment]
Linking your gist here:
https://gist.github.com/anonymous/04c923a2171d4e1f44231c3510ddf981

I have not used djoser so I am not sure, however, looking at the stacktrace, it appears to be an exception coming from DRF schemas. I suggest opening an issue on Django REST Framework and provide a failing test to demonstrate the bug. 
```
File "/Home/uname/.virtualenvs/openx/lib/python3.5/site-packages/rest_framework/schemas.py" in get_description
  402.         method_docstring = getattr(view, method_name, None).__doc__

Exception Type: TypeError at /api-docs/
Exception Value: getattr(): attribute name must be string
Request information:
```

**Comment by marcgibbons** [comment]
Did a bit of digging on this, looks like a fix has been made in the djoser package: https://github.com/sunscrapers/djoser/pull/172 but has not been released to PyPI.

With that said, in DRF `schemas.py` https://github.com/tomchristie/django-rest-framework/blob/06df61e38c6ed99732007b0e9f3cc26e8317389e/rest_framework/schemas.py#L401, we could probably add an additional check to verify that the `method_name` is an instance of str() rather than trust the view. This seems like an edge case though...

**Comment by marcgibbons** [comment]
Looks like djoser pushed to pypi:
https://github.com/sunscrapers/djoser/pull/172#issuecomment-269964656
