### ISSUE TITLE
Authentication Error: UserView queryset attribute

### ISSUE THREAD

**Issue by dvreed77** [marcgibbons/django-rest-swagger#621]
I am trying to get Django Swagger to work with my token based authentication.  I am getting this strange error:

```
500 : AssertionError at /swagger 'UserView' should either include a `queryset` attribute, or override the `get_queryset()` method. 
```

Any help would be much appreciated.

**Comment by marcgibbons** [comment]
@dvreed77 This is occurring likely because you are using a generic API view without a serializer, which is required by Django REST Framework. Consider providing a serializer class to your view or switching to a non-generic view.

http://www.django-rest-framework.org/api-guide/generic-views/#genericapiview
