### ISSUE TITLE
Endpoints with custom permissions classes are not mapped

### ISSUE THREAD

**Issue by raulgonzm** [marcgibbons/django-rest-swagger#633]
I'm using django-rest-swagger version 2.1.1.
I have several endpoints created with DRF generics class and custom permissions added to permission_classes class attribute.

This endpoints are mapped by swagger UI before add this custom permission classes. If I add any of this custom permissions the endpoint dissapear of swagger UI.

What can I do to this endpoints in order to be able to detected by Swagger?

**Comment by marcgibbons** [comment]
If the endpoints are disappearing, then presumably you are correctly including the request in your generator. Note that permissions will be enforced as though the current user was accessing the endpoint when accessing the spec.

**Comment by raulgonzm** [comment]
Hi Marc,

I don't know if I understand you correctly. Do you mean "correctly" or "incorrectly?

I've not created any generator. I've only created the api schema through get_swagger_view function in api urls file.

Is it necessary create this generator? Where I can find doc about generators?

Thanks in advance Marc.

**Comment by marcgibbons** [comment]
@raulgonzm Sorry my answer wasn't clear. Yes, I did mean "correctly" - the shortcut to the view passes in the request by default, so that is fine. You can optionally remove it if you wish not to enforce the permissions on your schema by defining your own view. By omitting the request, all your routes will render, however, if you depend on the `request` object in your serializers, you may get some errors.

The docs on schema generation are here: http://www.django-rest-framework.org/api-guide/schemas/#using-an-explicit-schema-view

What are your permission classes doing?

**Comment by raulgonzm** [comment]
Don't worry @marcgibbons

My permission class inherit from BasePermission of DRF. It is only check user request id if the same that the one we are trying to access through url. It don't do anything more.

It would be necessary create a schema generator to get this?

**Comment by marcgibbons** [comment]
I see. The endpoints will probably evaluate as not having permission if you're evaluating the incoming URL.

Perhaps try making an explicit schema view and not pass in the request? This will bypass the permission classes.

**Comment by raulgonzm** [comment]
Hi @marcgibbons,

Could you enlighten me with a simple sample? or could you send me something of doc?

Thank you in advance.

**Comment by marcgibbons** [comment]
Yes this is documented:
http://www.django-rest-framework.org/api-guide/schemas/#using-an-explicit-schema-view
http://marcgibbons.github.io/django-rest-swagger/schema/#advanced-usage

Only difference in your case, is to not pass in `request` into the schema generator. This will by-pass permission enforcement.
